name: Building For Linux

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  BUILD_TYPE: Release
  QWT_INCLUDE_DIR: ${{ github.workspace }}/source_code/Vendors/Qwt/src
  QWT_LIBRARY_RELEASE: ${{ github.workspace }}/source_code/Vendors/Qwt/lib/libqwt.so
  #QWT_LIBRARY_DEBUG: ${{ github.workspace }}/source_code/Vendors/Qwt/x64/Debug/qwtd.lib
  #DLL_DIR: ${{ github.workspace }}/source_code/Vendors/RequiredDLLs/

jobs:
  buildUsingCMake:
    name: buildUsingCMakeJob
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.12.11'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_DIR=${{env.QT_DIR}} -DQWT_INCLUDE_DIR=${{env.QWT_INCLUDE_DIR}} -DQWT_LIBRARY_RELEASE=${{env.QWT_LIBRARY_RELEASE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      